### ISSUE TITLE
No tracking information available error

### ISSUE THREAD

**Issue by grieserl** [gabrielbull/php-ups-api#106]
Hello, I am receiving the following error:
InvalidResponseException in Request.php line 131:
Failure: No tracking information available (151044)

when trying to track an order that UPS does not have tracking info for. The error is preventing my code from executing further. After tracing the error, I found that it occurs at line 94 of Tracking.php: 

$this->response = $this->getRequest()->request($access, $request, $this->compileEndpointUrl(self::ENDPOINT));

I've managed to correct the error by putting a try catch around that section of code but I doubt that's an "ideal" solution. It looks like there may be some error handling set up for that function already but most of the code is over my head so I haven't been able to make sense of it.

**Comment by stefandoorn** [comment]
Hi @grieserl, actually the method using try / catch is perfect. 

The problem is that UPS returns this as an error, so we also handle it as an error. If not, we have to check for specific error codes from UPS (which can change) to put specific behavior on. Using the try / catch method, you can actually decide yourself what to do when a certain error comes up. 

So e.g. you can return false when the exception is thrown with error code 151044 as it says no information is available, while you throw an exception on all other cases as that seems something odd. 

It would be nicer if UPS e.g. returns nodes telling that zero results were found, but that's not how it works unfortunately. Their reasoning is probably that it's not necessary for an external application to just randomly try shipping codes, probably you know which orders / shipments have a certain code and you can check specifically on these tracking codes.

Hope this helps :)

**Comment by stefandoorn** [comment]
P.S. The error handling we basically put around it consists of two parts: first it checks for an empty response which is in all cases problematic, and then it checks for a normal response with an error code. If that's the case, we parse the message and code and throw an exception. Because we split them, we can really tell the exception the error code, which should make easier handling:

````
try {
    $result = $api->track('blabla');
} catch (Exception $e) {
    $message = $e->getMessage();
    $code = $e->getCode();
}
````
