### ISSUE TITLE
Tons of assertions on phpunit test results

### ISSUE THREAD

**Issue by DasWookie** [gabrielbull/php-ups-api#135]
Before starting to implement the php-ups-api into my app, I wanted to run the tests to make sure things were looking good. The results I'm getting however aren't what I was hoping to see... namely 422 assertions in the test results:
```
[tests]# phpunit --verbose --bootstrap bootstrap.php Ups/Tests/
PHPUnit 5.7.5 by Sebastian Bergmann and contributors.

Runtime:       PHP 5.6.27

...............................................................  63 / 156 ( 40%)
............................................................... 126 / 156 ( 80%)
..............................                                  156 / 156 (100%)

Time: 330 ms, Memory: 7.75MB

OK (156 tests, 422 assertions)

```

I'm not familiar with PHPunit so don't know how concerned I should be about this, but it's not confidence inspiring in my setup. I BELIEVE my setup is good, as the tests are running, I'm more used to the Perl model of testing where things are reported as PASS / FAIL and I'm looking at an assertion as a fail... maybe I'm being concerned over nothing tho.

**Comment by stefandoorn** [comment]
@DasWookie, 422 assertions means actually 422 checks. As you only see dots above, that means they have passed without any error, warning or other failure. In that case you would have seen letters instead of dots or even a hard break of the test. 

The 422 assertions are placed in 156 separate tests, meaning most tests have multiple assertions (e.g. checking several characteristics of the return values). 

We can still extend the suite, but the basics are covered quite well. Luckily UPS is also conservative in making API changes, which helps also a bit.

**Comment by DasWookie** [comment]
Gotcha. OK thank you for the clarification.
