### ISSUE TITLE
Documentation for Shipping Method

### ISSUE THREAD

**Issue by ConvarDeutschland** [gabrielbull/php-ups-api#61]
Hello can you help with an exemple on using the Shipping method.
Tracking is working well, but i need to implement the Shipment now.

Thanks

**Comment by stefandoorn** [comment]
Hi @ConvarDeutschland, maybe the answer in #39 can help you on the way? I'm willing to add documentation later this week, but can't get that done today I'm afraid.

**Comment by ConvarDeutschland** [comment]
Hi stefandoorn,

Thanks for the info, this help me a lot. Shipping is working now and return me some information.
I did some little changes in the exemple to make it work.

The only thing that make me problems now is the line:

$shipment_digest = $result->ShipmentDigest; //can be used to print labels

What is the content of $shipment_digest? The label itself base64 coded as gif,pdf,jpg?

When I base64 decode it I get a strange Text, with readable parts, so I suppose it is not directly the label itself as an image. but what is it then.

I tried jpg, gif, and pdf but this do not seem to be what is stored in this variable.

Do you know what is returned there ?
Or do I need to request the label as a GIF perhaps? if so can you tell me how to add this to the shippment request?

Best regards

**Comment by stefandoorn** [comment]
Hi @ConvarDeutschland 

How it works:
* You need to do a 'confirm' request with all the shipment information.
* If that one is accepted (no errors etc) then you get a result with a ShipmentDigest in it
* That shipment digest, you just insert it into the 'accept' request: `$accept = $this->api->accept($confirm->ShipmentDigest);`
* In the response you then get, you will find base 64 encoded images with the label.

The idea is that you need to use the confirm request to add data to UPS and to make sure they accept it without any errors. Then you use the accept request to accept their reply and make it definitive. Until you use the accept request, nothing is finalized for that shipment.

**Comment by ConvarDeutschland** [comment]
Hi stefandoorn,

Ok get it!  It works now.But what is not working is the "ReturnService"
If I add the ReturnService to the request I get the error
InvalidResponseException in Request.php line 131:
Failure: The XML document is well formed but the document is not valid (10002)

But it is not clear why the document is not valid anymore?
Do I need to change something in the Shipping request to make a Return? 

Here the souce if somebody need to set it up:

<pre>
$shipping = new Shipping($accesskey, $userid, $password, true);		
		
try {
	$shipment = new Shipment();			

	$shipper = $shipment->getShipper();
	$shipper->setShipperNumber($userid);
	$shipper->setName('COMPANY_NAME');
	$shipper->setAttentionName('COMPANY_NAME');
	$shipper->setPhoneNumber('0123456789');
	$shipperAddress = $shipment->getShipper()->getAddress();
	$shipperAddress->setPostalCode('POSTALCODE');
	$shipperAddress->setAddressLine1('BUSINESS ADDRESS 1');
	$shipperAddress->setAddressLine2('BUSINESS ADDRESS 2');
	$shipperAddress->setCity('CITY');
	$shipperAddress->setCountryCode('DE');			

	$address = new Address();
	$address->setPostalCode('POSTALCODE');
	$address->setAddressLine1('BUSINESS ADDRESS 1');
	//$address->setAddressLine2('BUSINESS ADDRESS 2');
	$address->setCity('CITY');
	$address->setCountryCode('DE');
	$shipFrom = new ShipFrom();
	$shipFrom->setAddress($address);
	$shipFrom->setCompanyName('COMPANY_NAME');
	$shipment->setShipFrom($shipFrom);
	$ship = $shipment->getShipFrom();
	$ship->CompanyName = 'COMPANY_NAME';				

	$shipTo = $shipment->getShipTo();
	$shipTo->setAttentionName('FIRSTNAME LASTNAME');
	$shipTo->setReceivingAddressName('FIRSTNAME LASTNAME');
	$shipTo->setPhoneNumber('999999999');
	$shipTo->setEmailAddress('EMAIL@DOMAIM.COM');
	$shipTo->setCompanyName('COMPANY_NAME');
	$shipToAddress = $shipTo->getAddress();
	$shipToAddress->setPostalCode('POSTALCODE');
	$shipToAddress->setAddressLine1('ADDRESS 1');
	//$shipToAddress->setAddressLine2('ADDRESS 2');
	$shipToAddress->setCity('CITY');
	$shipToAddress->setCountryCode('FR');
	$shipment->setShipTo($shipTo);
	
	//Add package
	
	$unitofweight = new UnitOfMeasurement;
	$unitofweight->setCode(UnitOfMeasurement::UOM_KGS);
	
	$package = new Package();
	$package->getPackagingType()->setCode(PackagingType::PT_PACKAGE);
	$package->getPackageWeight()->setWeight('10');
	$package->getPackageWeight()->setUnitOfMeasurement($unitofweight);			

	$dimensions = new Dimensions();
	$dimensions->setHeight(20);
	$dimensions->setWidth(21);
	$dimensions->setLength(33);

	$unit = new UnitOfMeasurement;
	$unit->setCode(UnitOfMeasurement::UOM_CM);			

	$dimensions->setUnitOfMeasurement($unit);
	$package->setDimensions($dimensions);
	$shipment->addPackage($package);
	
	$referencenumber=new ReferenceNumber;
	//$referencenumber->setCode('RZ');
	$referencenumber->setValue('MYREFNUMBER_1');
	$shipment->setReferenceNumber($referencenumber);

	$service= new Service();			
	$service->setCode(Service::S_STANDARD);			
	$shipment->setService($service);
	
	/*$returnservice = new ReturnService;
	$returnservice->setCode(ReturnService::PRINT_RETURN_LABEL_PRL);
	$shipment->setReturnService($returnservice);*/

	$billshipper= new BillShipper();
	$billshipper->setAccountNumber($userid);
	$prepaid=new Prepaid(); 
	$prepaid->setBillShipper($billshipper);

	$paymentInformation = new PaymentInformation;
	$paymentInformation->setPrepaid($prepaid);
	
	$shipment->setPaymentInformation($paymentInformation);
	
	//This will create UPS shipment			
	$result = $shipping->confirm('nonvalidate', $shipment);
	
	$shipment_charges = $result->ShipmentCharges->TotalCharges->MonetaryValue;
	$shipment_weight = $result->BillingWeight->Weight." ".$result->BillingWeight->UnitOfMeasurement->Code;
	$tracking_number = $result->ShipmentIdentificationNumber;
	$shipment_digest = $result->ShipmentDigest; //can be used to print labels
	
	$accept = $shipping->accept($shipment_digest);
		
	$tracking_number = $accept->PackageResults->TrackingNumber;
	$imageformat = $accept->PackageResults->LabelImage->LabelImageFormat->Code;
		
	$base64image = $accept->PackageResults->LabelImage->GraphicImage;
	
	$image = base64_decode($base64image);
		
	$response = Response::make($image,200);
		
	// Set the mime type for the response.
	// We now use the Image class for this also.
	$response->header('content-type', 'image/gif');
	
	return $response;
				
} catch (Exception $e) {
	$error = $e->getMessage();
}
</pre>

**Comment by stefandoorn** [comment]
@ConvarDeutschland Hard to say, I'm reading through your code and making a comparison with mine, but I don't see an obvious problem. Could you add some debugging in the Request class to get the full response on your screen (XML response)? I think it will show you some more information you might need.

All classes also support the addition to insert a logger object, example: 

````
// Load logger
        $log = new \Monolog\Logger('ups');
        $log->pushHandler(new \Monolog\Handler\StreamHandler(DIR_MONOLOG . 'ups.log', \Monolog\Logger::DEBUG));

        // Load Shipping API
        $this->api = new Ups\Shipping(
            $key,
            $username,
            $password,
            $useIntegration,
            null,
            $log
        );
````

Obviously I'm using Monolog in this example, but you can also use any other PSR-3 compatible logger. Anyway, it makes it easy for me while developing to find the exact requests and responses I'm getting in a log file, without the access credentials being saved into that file. 

Pretty often errors happen due to invalid data being inserted. The documentation states most of the requirements to your data, but it's a tedious job to read through all of it. Some debugging using a logger makes things way easier.

**Comment by ConvarDeutschland** [comment]
@stefandoorn Thanks for you tip with the log of the XML Response. In this file the Missing field was given. It was "ShipmentConfirmRequest\Shippment\Package\Description". After adding this field with

$package->setDescription('Return');

the return label was generated.
Thanks again for your really good support.
The issue can be closed now.

**Comment by rafacuest** [comment]
My gratitude to @ConvarDeutschland and @stefandoorn related to the ReturnService issue, I owe you a beer.

**Comment by lchhieu** [comment]
This is code shpping of I,  but I get the error:
_Failure: Missing or invalid shipper number (120100)_
`
$shipping = new Shipping($accesskey, $userid, $password, true);
		try {
			$shipment = new Shipment();

			$shipper = $shipment->getShipper();
			$shipper->setShipperNumber($userid);
			$shipper->setName('COMPANY_NAME');
			$shipper->setAttentionName('COMPANY_NAME');
			$shipper->setPhoneNumber('0123456789');
			$shipperAddress = $shipment->getShipper()->getAddress();
			$shipperAddress->setPostalCode('10000');
			$shipperAddress->setAddressLine1('3552 Davis Drive');
			$shipperAddress->setCity('Morrisville');
			$shipperAddress->setStateProvinceCode('NC');
			$shipperAddress->setCountryCode('US');

			$address = new Address();
			$address->setPostalCode('27613');
			$address->setAddressLine1('12341 Strickland RdSte 106');
			//$address->setAddressLine2('BUSINESS ADDRESS 2');
			$address->setCity('Raleigh');
			$address->setCountryCode('US');
			$shipFrom = new ShipFrom();
			$shipFrom->setAddress($address);
			$shipFrom->setCompanyName('COMPANY_NAME');
			$shipment->setShipFrom($shipFrom);
			$ship = $shipment->getShipFrom();
			$ship->CompanyName = 'COMPANY_NAME';

			$shipTo = $shipment->getShipTo();
			$shipTo->setAttentionName('FIRSTNAME LASTNAME');
			$shipTo->setReceivingAddressName('FIRSTNAME LASTNAME');
			$shipTo->setPhoneNumber('999999999');
			$shipTo->setEmailAddress('EMAIL@DOMAIM.COM');
			$shipTo->setCompanyName('COMPANY_NAME');
			$shipToAddress = $shipTo->getAddress();
			$shipToAddress->setPostalCode('08817');
			$shipToAddress->setAddressLine1('100 Plainfield Ave Suite B3 Edison NJ 08817');
			//$shipToAddress->setAddressLine2('ADDRESS 2');
			$shipToAddress->setCity('Edison');
			$shipToAddress->setCountryCode('US');
			$shipment->setShipTo($shipTo);

			//Add package

			$unitofweight = new UnitOfMeasurement;
			$unitofweight->setCode(UnitOfMeasurement::UOM_KGS);

			$package = new Package();
			$package->getPackagingType()->setCode(PackagingType::PT_PACKAGE);
			$package->getPackageWeight()->setWeight('10');
			$package->getPackageWeight()->setUnitOfMeasurement($unitofweight);

			$dimensions = new Dimensions();
			$dimensions->setHeight(20);
			$dimensions->setWidth(21);
			$dimensions->setLength(33);

			$unit = new UnitOfMeasurement;
			$unit->setCode(UnitOfMeasurement::UOM_CM);

			$dimensions->setUnitOfMeasurement($unit);
			$package->setDimensions($dimensions);
			$shipment->addPackage($package);

			$referencenumber=new ReferenceNumber;
			//$referencenumber->setCode('RZ');
			$referencenumber->setValue('MYREFNUMBER_1');
			$shipment->setReferenceNumber($referencenumber);

			$service= new Service();
			$service->setCode("03");
			$shipment->setService($service);


			/*$returnservice = new ReturnService;
            $returnservice->setCode(ReturnService::PRINT_RETURN_LABEL_PRL);
            $shipment->setReturnService($returnservice);*/

			$billshipper= new BillShipper();
			$billshipper->setAccountNumber($userid);
			$prepaid=new Prepaid();
			$prepaid->setBillShipper($billshipper);

			$paymentInformation = new PaymentInformation;
			$paymentInformation->setPrepaid($prepaid);

			$shipment->setPaymentInformation($paymentInformation);

			//This will create UPS shipment
			$result = $shipping->confirm('nonvalidate', $shipment);

			$shipment_charges = $result->ShipmentCharges->TotalCharges->MonetaryValue;
			$shipment_weight = $result->BillingWeight->Weight." ".$result->BillingWeight->UnitOfMeasurement->Code;
			$tracking_number = $result->ShipmentIdentificationNumber;
			$shipment_digest = $result->ShipmentDigest; //can be used to print labels

			$accept = $shipping->accept($shipment_digest);

			$tracking_number = $accept->PackageResults->TrackingNumber;
			$imageformat = $accept->PackageResults->LabelImage->LabelImageFormat->Code;

			$base64image = $accept->PackageResults->LabelImage->GraphicImage;

			$image = base64_decode($base64image);

			$response = Response::make($image,200);

			// Set the mime type for the response.
			// We now use the Image class for this also.
			$response->header('content-type', 'image/gif');

			echo "<pre>"; echo "dung";
			print_r($response);
			echo "</pre>";

		} catch (Exception $e) {
			echo "<pre>"; echo "sai";
			print_r($e);
			$error = $e->getMessage();
			echo "</pre>";
		}`

**Comment by stefandoorn** [comment]
The error says it: the shipper number is missing, or if present, is wrong. It's a code you get from UPS, and it's not your username.

**Comment by lchhieu** [comment]
_ Failure: Shipment/ReferenceNumber is not allowed for this shipment (120541)_
You see this is shipper number
http://i.imgur.com/VERBLEx.png

code of my
$shipping = new Shipping($accesskey, $userid, $password, true);

		try {
			$shipment = new Shipment();

			$shipper = $shipment->getShipper();
			$shipper->setShipperNumber($shipperNumber);
			$shipper->setName('COMPANY_NAME');
			$shipper->setAttentionName('COMPANY_NAME');
			$shipper->setPhoneNumber('0123456789');
			$shipperAddress = $shipment->getShipper()->getAddress();
			$shipperAddress->setPostalCode('10000');
			$shipperAddress->setAddressLine1('3552 Davis Drive');
			$shipperAddress->setCity('Morrisville');
			$shipperAddress->setStateProvinceCode('NC');
			$shipperAddress->setCountryCode('US');

			$address = new Address();
			$address->setPostalCode('27613');
			$address->setAddressLine1('12341 Strickland RdSte 106');
			//$address->setAddressLine2('BUSINESS ADDRESS 2');
			$address->setCity('Raleigh');
			$address->setCountryCode('US');
			$shipFrom = new ShipFrom();
			$shipFrom->setAddress($address);
			$shipFrom->setCompanyName('COMPANY_NAME');
			$shipment->setShipFrom($shipFrom);
			$ship = $shipment->getShipFrom();
			$ship->CompanyName = 'COMPANY_NAME';

			$shipTo = $shipment->getShipTo();
			$shipTo->setAttentionName('FIRSTNAME LASTNAME');
			$shipTo->setReceivingAddressName('FIRSTNAME LASTNAME');
			$shipTo->setPhoneNumber('999999999');
			$shipTo->setEmailAddress('EMAIL@DOMAIM.COM');
			$shipTo->setCompanyName('COMPANY_NAME');
			$shipToAddress = $shipTo->getAddress();
			$shipToAddress->setPostalCode('08817');
			$shipToAddress->setAddressLine1('100 Plainfield Ave Suite B3 Edison NJ 08817');
			//$shipToAddress->setAddressLine2('ADDRESS 2');
			$shipToAddress->setCity('Edison');
			$shipToAddress->setCountryCode('US');
			$shipment->setShipTo($shipTo);

			//Add package

			$unitofweight = new UnitOfMeasurement;
			$unitofweight->setCode(UnitOfMeasurement::UOM_KGS);

			$package = new Package();
			$package->getPackagingType()->setCode(PackagingType::PT_PACKAGE);
			$package->getPackageWeight()->setWeight('10');
			$package->getPackageWeight()->setUnitOfMeasurement($unitofweight);

			$dimensions = new Dimensions();
			$dimensions->setHeight(20);
			$dimensions->setWidth(21);
			$dimensions->setLength(33);

			$unit = new UnitOfMeasurement;
			$unit->setCode(UnitOfMeasurement::UOM_CM);

			$dimensions->setUnitOfMeasurement($unit);
			$package->setDimensions($dimensions);
			$shipment->addPackage($package);

			$referencenumber=new ReferenceNumber;
			//$referencenumber->setCode('RZ');
			$referencenumber->setValue('MYREFNUMBER_1');
			$shipment->setReferenceNumber($referencenumber);

			$service= new Service();
			$service->setCode("03");
			$shipment->setService($service);


			/*$returnservice = new ReturnService;
            $returnservice->setCode(ReturnService::PRINT_RETURN_LABEL_PRL);
            $shipment->setReturnService($returnservice);*/

			$billshipper= new BillShipper();
			$billshipper->setAccountNumber($userid);
			$prepaid=new Prepaid();
			$prepaid->setBillShipper($billshipper);

			$paymentInformation = new PaymentInformation;
			$paymentInformation->setPrepaid($prepaid);

			$shipment->setPaymentInformation($paymentInformation);

			//This will create UPS shipment
			$result = $shipping->confirm('nonvalidate', $shipment);

			$shipment_charges = $result->ShipmentCharges->TotalCharges->MonetaryValue;
			$shipment_weight = $result->BillingWeight->Weight." ".$result->BillingWeight->UnitOfMeasurement->Code;
			$tracking_number = $result->ShipmentIdentificationNumber;
			$shipment_digest = $result->ShipmentDigest; //can be used to print labels

			$accept = $shipping->accept($shipment_digest);

			$tracking_number = $accept->PackageResults->TrackingNumber;
			$imageformat = $accept->PackageResults->LabelImage->LabelImageFormat->Code;

			$base64image = $accept->PackageResults->LabelImage->GraphicImage;

			$image = base64_decode($base64image);

			$response = Response::make($image,200);

			// Set the mime type for the response.
			// We now use the Image class for this also.
			$response->header('content-type', 'image/gif');

			echo "<pre>"; 
			print_r($response);
			echo "</pre>";

		} catch (Exception $e) {
			echo "<pre>";
			print_r($e);
			$error = $e->getMessage();
			echo "</pre>";
		}`

**Comment by stefandoorn** [comment]
I think in US you need reference number per package, not at shipment level (but I'm not totally sure). In EU this is different. Best is to contact UPS API support for this, as I'm not aware of the rules in US (I'm from EU).

**Comment by squatto** [comment]
For those that happen upon this looking for an answer, @stefandoorn is correct: you have to set the reference number on the package or you will get an error back from UPS.

Wrong:

`$referenceNumber = new ReferenceNumber();
$referenceNumber->setCode(ReferenceNumber::CODE_TRANSACTION_REFERENCE_NUMBER);
$referenceNumber->setValue('Reference Number Here');

// RIGHT:
$shipment->getPackages()[0]->setReferenceNumber($referenceNumber);

// WRONG:
$shipment->setReferenceNumber($referenceNumber);
`

**Comment by 4455667788** [comment]
Hello below is my code and i face issue while creating shipping label , please do guide me 

The error is : Notice: Undefined variable: return in /home/ocanalytica/public_html/ups/ups-test/check.php on line 92

Notice: Undefined variable: return in /home/ocanalytica/public_html/ups/ups-test/check.php on line 162
errorobject(Ups\Exception\InvalidResponseException)#52 (7) { ["message":protected]=> string(75) "Failure: Shipment/ReferenceNumber is not allowed for this shipment (120541)" ["string":"Exception":private]=> string(0) "" ["code":protected]=> int(120541) ["file":protected]=> string(89) "/home/ocanalytica/public_html/ups/ups-test/UPS/vendor/gabrielbull/ups-api/src/Request.php" ["line":protected]=> int(145) ["trace":"Exception":private]=> array(2) { [0]=> array(6) { ["file"]=> string(90) "/home/ocanalytica/public_html/ups/ups-test/UPS/vendor/gabrielbull/ups-api/src/Shipping.php" ["line"]=> int(81) .............


My code is : 
$accessKey = '************';
$userId = '*****';
$password = '786@Ups';

// Start shipment
$shipment = new Ups\Entity\Shipment;



// Set shipper
$shipper = $shipment->getShipper();
$shipper->setShipperNumber('69R237');
$shipper->setName('Profiix');
$shipper->setAttentionName('Umer');
$shipperAddress = $shipper->getAddress();
$shipperAddress->setAddressLine1('11709 South Orange Blossom Trail');
$shipperAddress->setPostalCode('32837');
$shipperAddress->setCity('Orlando');
$shipperAddress->setStateProvinceCode('FL'); // required in US
$shipperAddress->setCountryCode('US');
$shipper->setAddress($shipperAddress);
$shipper->setEmailAddress('umer.shahzad.softwareengineer@gmail.com'); 
$shipper->setPhoneNumber('16092142857');
$shipment->setShipper($shipper);



// To address
$address = new \Ups\Entity\Address();
$address->setAddressLine1('591 Grand Avenue');
$address->setPostalCode('92069');
$address->setCity('San Marcos');
$address->setStateProvinceCode('CA');  // Required in US
$address->setCountryCode('US');
$shipTo = new \Ups\Entity\ShipTo();
$shipTo->setAddress($address);
$shipTo->setCompanyName('profiix');
$shipTo->setAttentionName('profiix Franchise');
$shipTo->setEmailAddress('umer.shahzad.softwareengineer@gmail.com'); 
//$shipTo->setPhoneNumber('');
$shipment->setShipTo($shipTo);

// From address
$address = new \Ups\Entity\Address();
$address->setAddressLine1('11709 S Orange Blossom Trail #106');
$address->setPostalCode('32837');
$address->setCity('Orlando');
$address->setStateProvinceCode('FL');  
$address->setCountryCode('US');
$shipFrom = new \Ups\Entity\ShipFrom();
$shipFrom->setAddress($address);
$shipFrom->setName('Umer Shahzad');
$shipFrom->setAttentionName($shipFrom->getName());
$shipFrom->setCompanyName($shipFrom->getName());
$shipFrom->setEmailAddress('umer.shahzad@ocanalytica.com');
$shipFrom->setPhoneNumber('16092142857');
$shipment->setShipFrom($shipFrom);

/*
// Sold to
$address = new \Ups\Entity\Address();
$address->setAddressLine1('4002 Promenade Square Dr');
$address->setPostalCode('32837');
$address->setCity('Orlando');
$address->setCountryCode('US');
$address->setStateProvinceCode('FL');
$soldTo = new \Ups\Entity\SoldTo;
$soldTo->setAddress($address);
$soldTo->setAttentionName('Pro');
$soldTo->setCompanyName($soldTo->getAttentionName());
$soldTo->setEmailAddress('a.kungfu.man.umer@gmail.com');
$soldTo->setPhoneNumber('16092142857');
$shipment->setSoldTo($soldTo);
*/

// Set service
$service = new \Ups\Entity\Service;
$service->setCode(\Ups\Entity\Service::S_STANDARD);
$service->setDescription($service->getName());
$shipment->setService($service);

//$return ='';

// Mark as a return (if return)
if ($return) {
    $returnService = new \Ups\Entity\ReturnService;
    $returnService->setCode(\Ups\Entity\ReturnService::PRINT_RETURN_LABEL_PRL);
    $shipment->setReturnService($returnService);
}

// Set description
$shipment->setDescription('For testing');


/*
// Add Package
    $package = new \Ups\Entity\Package();
    $package->getPackagingType()->setCode(\Ups\Entity\PackagingType::PT_PACKAGE);
    $package->getPackageWeight()->setWeight(1);
    $unit = new \Ups\Entity\UnitOfMeasurement;
    $unit->setCode(\Ups\Entity\UnitOfMeasurement::UOM_KGS);
    $package->getPackageWeight()->setUnitOfMeasurement($unit);


// Set Package Service Options
$packageServiceOptions = new \Ups\Entity\PackageServiceOptions();
$packageServiceOptions->setShipperReleaseIndicator(true);
$package->setPackageServiceOptions($packageServiceOptions);

    // Set dimensions
    $dimensions = new \Ups\Entity\Dimensions();
    $dimensions->setHeight(1);
    $dimensions->setWidth(1);
    $dimensions->setLength(1);
    $unit = new \Ups\Entity\UnitOfMeasurement;
    $unit->setCode(\Ups\Entity\UnitOfMeasurement::UOM_IN);
    $dimensions->setUnitOfMeasurement($unit);
    $package->setDimensions($dimensions);

*/
// Add Package
$package = new \Ups\Entity\Package();
$package->getPackagingType()->setCode(\Ups\Entity\PackagingType::PT_PACKAGE);
$package->getPackageWeight()->setWeight(10);
$unit = new \Ups\Entity\UnitOfMeasurement;
$unit->setCode(\Ups\Entity\UnitOfMeasurement::UOM_KGS);
$package->getPackageWeight()->setUnitOfMeasurement($unit);

// Set Package Service Options
$packageServiceOptions = new \Ups\Entity\PackageServiceOptions();
$packageServiceOptions->setShipperReleaseIndicator(true);
$package->setPackageServiceOptions($packageServiceOptions);

// Set dimensions
$dimensions = new \Ups\Entity\Dimensions();
$dimensions->setHeight(10);
$dimensions->setWidth(10);
$dimensions->setLength(10);
$unit = new \Ups\Entity\UnitOfMeasurement;
$unit->setCode(\Ups\Entity\UnitOfMeasurement::UOM_CM);
$dimensions->setUnitOfMeasurement($unit);
$package->setDimensions($dimensions);


// Add descriptions because it is a package
$package->setDescription('Package weight');

// Add this package
$shipment->addPackage($package);

$order_id = '69R237';

// Set Reference Number
$referenceNumber = new \Ups\Entity\ReferenceNumber;
if ($return) {
    $referenceNumber->setCode(\Ups\Entity\ ReferenceNumber::CODE_RETURN_AUTHORIZATION_NUMBER);
    $referenceNumber->setValue($return_id);
} else {
    $referenceNumber->setCode(\Ups\Entity\ReferenceNumber::CODE_INVOICE_NUMBER);
    $referenceNumber->setValue($order_id);
}
$shipment->setReferenceNumber($referenceNumber);


// Set payment information
$shipment->setPaymentInformation(new \Ups\Entity\PaymentInformation('prepaid', (object)array('AccountNumber' => '69R237')));

// Ask for negotiated rates (optional)
$rateInformation = new \Ups\Entity\RateInformation;
$rateInformation->setNegotiatedRatesIndicator(1);
$shipment->setRateInformation($rateInformation);

// Get shipment info
try {
    $api = new Ups\Shipping($accessKey, $userId, $password); 

    $confirm = $api->confirm(\Ups\Shipping::REQ_VALIDATE, $shipment);
    var_dump($confirm); // Confirm holds the digest you need to accept the result
    
    if ($confirm) {
        $accept = $api->accept($confirm->ShipmentDigest);
        var_dump($accept); // Accept holds the label and additional information
    }
} catch (\Exception $e) {
    echo "error";
    var_dump($e);
}
